stages:
  - test
  - build
  - docker


go-test:
  stage: test
  image: golang:1.27
  tags:
    - docker
  script:
    - go version
    - go mod download
    - go test ./...

go-build:
  stage: build
  image: golang:1.27
  tags:
    - docker
  script:
    - go mod download
    - go build -o devops-shop ./cmd/api
  artifacts:
    paths:
      - devops-shop

docker-build:
  stage: docker 
  image:
    name: docker:cli
    pull_policy: if-not-present
  tags:
    - docker
  services:
    - name: docker:dind
      pull_policy: if-not-present
      command:
        - "--insecure-registry=192.168.64.14:5050"


  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker version
    - docker login -u "$CI_REGISTERY_USER" -p "$CI_REGISTERY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:1.0" .
    - docker push "$CI_REGISTRY_IMAGE:1.0"
