stages:
  - test
  - build
  - docker
  - deploy

go-test:
  stage: test
  image: golang:1.27
  tags:
    - docker
  script:
    - go version
    - go mod download
    - go test ./...

go-build:
  stage: build
  image: golang:1.27
  tags:
    - docker
  script:
    - go mod download
    - go build -o devops-shop ./cmd/api
  artifacts:
    paths:
      - devops-shop

docker-build:
  stage: docker
  image:
    name: docker:cli
    pull_policy: if-not-present
  tags:
    - docker
  services:
    - name: docker:dind
      pull_policy: if-not-present
      command:
        - "--insecure-registry=192.168.64.14:5050"
        - "--ipv6=false"
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    BUILDX_NO_DEFAULT_ATTESTATIONS: "1"
  resource_group: docker-push-$CI_REGISTRY_IMAGE
  script:
    - docker version
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - |
      if [ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]; then
        docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE:1.0"
        docker push "$CI_REGISTRY_IMAGE:1.0"
      fi



frontend-docker-build:
  stage: docker
  image:
    name: docker:cli
    pull_policy: if-not-present
  tags:
    - docker
  services:
    - name: docker:dind
      pull_policy: if-not-present
      command:
        - "--insecure-registry=192.168.64.14:5050"
        - "--ipv6=false"
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    BUILDX_NO_DEFAULT_ATTESTATIONS: "1"
  resource_group: docker-push-$CI_REGISTRY_IMAGE/frontend
  script:
    - docker version
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA" ./frontend
    - docker push "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA"
    - |
      if [ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]; then
        docker tag "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE/frontend:1.0"
        docker push "$CI_REGISTRY_IMAGE/frontend:1.0"
      fi


deploy:
  stage: deploy
  image: python:3.14-slim
  tags:
    - docker

  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends openssh-client
    - pip install --no-cache-dir ansible-core==2.20.7

    - mkdir -p "$HOME/.ssh"
    - chmod 700 "$HOME/.ssh"

    - printf '%s' "$SSH_PRIVATE_KEY_B64" | base64 -d > "$HOME/.ssh/deploy_key"
    - chmod 600 "$HOME/.ssh/deploy_key"

    - ssh-keygen -y -f "$HOME/.ssh/deploy_key" > /dev/null
    - ssh-keyscan -H 192.168.64.6 >> "$HOME/.ssh/known_hosts"

  script:
    - ansible --version
    - ansible-playbook -i ansible/inventory.ini ansible/site.yml -e "image_tag=$CI_COMMIT_SHA" -e "ansible_ssh_private_key_file=$HOME/.ssh/deploy_key"

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
