stages:
  - test
  - build
  - docker


go-test:
  stage: test
  image: golang:1.27
  script:
    - go version
    - go mod download
    - go test ./...

go-build:
  stage: build
  image: golang:1.27
  script:
    - go mod download
    - go build -o devops-shop ./cmd/api
  artifacts:
    paths:
      - devops-shop

docker-build:
  stage: docker 
  image: docker:cli
  tags:
    - docker
  services:
    - name: docker:dind
      pull_policy: if-not-present
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker version
    - docker build -t devops-shop:1.0 .
